# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55f5b252090158f24b47cd908529d456a318210bec65964de7a205191974c806bb297f045d34a30091b00286e4cbbfa7d0b8e2720132fdbc5f4833183cdf1cc3

test:
  secret_key_base: 8ec1ab2d6443d7138eb62ba90fc5f74fbebe41ea9ebda5192e1c32a9970e99445f202ed58b82b9a27ed3caca85130bcb43bd5480b1bc54786f152beb5d3993d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
